### ISSUE TITLE
Test Librarian service

### ISSUE THREAD

**Issue by saneros** [djavorek/software-testing#18]

**Comment by djavorek** [comment]
https://coveralls.io/github/djavorek/software-testing?branch=master
Here you can check the coverage (another branch can be selected, it is automatically updated after push)

Write JUnit tests into the service/src/test/ folder, the package name of the test should be the same as the package name of the tested class, the test class should be named: {tested-class-name}Test.java

Use #18 git branch for your work

Feel free to write comment and ask, if something is not clear I will write examples on your branch for it.

**Comment by djavorek** [comment]
It is finished finally, merged.
