### ISSUE TITLE
Test Reader service

### ISSUE THREAD

**Issue by saneros** [djavorek/software-testing#19]

**Comment by djavorek** [comment]
https://coveralls.io/github/djavorek/software-testing?branch=master
Here you can check the coverage (another branch can be selected, it is automatically updated after push)

**Comment by djavorek** [comment]
Use branch #19

**Comment by sormanzje** [comment]
I think I am done with this issue. In the #19 branch I did a pull request, the merge pull request is still remaining.

**Comment by djavorek** [comment]
I dont know why it wasnt closed before. Now it is.
