### ISSUE TITLE
Implement rest of the DAO and data structure

### ISSUE THREAD

**Issue by saneros** [djavorek/software-testing#20]
Implement data access object for the rest of the domain pojos, SQL initialisation scripts and sample data

- [x] Borrowing
- [x] User

**Comment by aronnagy** [comment]
I've done with the VERY early version of User DAO and a new "dao" branch.

**Comment by SzaboBalint01** [comment]
I'm done with the Borrowing DAO now. Can we close and merge the issue?

**Comment by djavorek** [comment]
Sorry, I forgot to check this issue (dint receive email)
If everything is ready, create a pull request
