### ISSUE TITLE
Cover the missing parts of Core modul with tests

### ISSUE THREAD

**Issue by djavorek** [djavorek/software-testing#34]
https://coveralls.io/github/djavorek/software-testing?branch=master
Here you can check the currently covered lines.

The goal is to reach 100% coverage.
If something not clear, write a comment or ask

**Comment by djavorek** [comment]
Use branch #34

**Comment by djavorek** [comment]
Create the pull request from #34 to master

**Comment by SzaboBalint01** [comment]
I have reached the 100% coverage, i think we can merge it now.
