### ISSUE TITLE
Create ER model

### ISSUE THREAD

**Issue by djavorek** [djavorek/software-testing#7]
Create ER model (diagram) according to the already created model classes.
If something is not clear, write a comment!

**Comment by djavorek** [comment]
I have a few advice:

- BorrowStatus table is **not required** (its just a Java Enum)
- Use the PK of referenced table as a ForeignKey (FK) when referencing another table (_for example_ in Book table: change **instances to instanceId (FK)**
- **Not sure**: We have added a parent reference to BookInstance after I created the class diagram (so you can tell by every BookInstance, to which Book it belongs). If it's okay in SQL, it should be added as FK too (It's a circular refeference: Book->BookInstance->Book)

If you are done, just copy it here as a comment.
Feel free to dispute or comment :D

**Comment by pidrro** [comment]
![erm](https://user-images.githubusercontent.com/43223035/46924041-4f1ea100-d018-11e8-9f39-1c9ca756531e.PNG)

About Fk : I think we don't put foreign keys in ER model, but I tried to add it somehow. If you have any other remarks, please comment

**Comment by djavorek** [comment]
Yep, you are right about FK, you dont have to write that there. Only change the referencing member of the table to the id of the referenced table. So dont write instances (String), use InstanceId (int) instead. Because you cant use types like, user and BookInstance in sql as variable types

**Comment by pidrro** [comment]
![erm](https://user-images.githubusercontent.com/43223035/46979059-7339bb00-d0c8-11e8-8a98-8cbe0741bea9.PNG)

**Comment by aronnagy** [comment]
Hi Guys!
I have to mention that these diagrams are **NOT** ER diagrams, but don't worry I created a new one (call it "alpha version").  

![softtester](https://user-images.githubusercontent.com/39951338/47961566-dfe00f80-e00d-11e8-91af-74fc9be72315.png)

If you have any problems @djavorek let me know and I'll fix it ASAP

P.S.: If it is necessary I can easily convert the ER into a Relational diagram (to an easier SQL implementation).

Have a nice day!

Aron

**Comment by djavorek** [comment]
That looks good, there are two things that need to be changed, because we merged some modifications in the last two days.
So check the current state of the model classes on the master branch.
The changes in short:
 - We added a new Boolean variable to the User class to know whether is it Librarian or Reader user
- We added a new Integer variable, to store how many copy of the book available currently

These changes were neccessary because we deleted Reader, Librarian and BookInstance classes.

Thank you Aron, feel free to ask

**Comment by aronnagy** [comment]
![8d41e521-bb23-4c7c-8d51-e643bbb94e81](https://user-images.githubusercontent.com/39951338/47963364-8a1a6000-e02b-11e8-90c1-52291d523736.jpeg)

Is it good like this?

**Comment by aronnagy** [comment]
Oopsie (szöveg in the Middle) :D 
![8c3841c1-dd2f-46f2-804a-19caf165e1f8](https://user-images.githubusercontent.com/39951338/47963381-d2d21900-e02b-11e8-88c7-1db0d8354688.jpeg)

Now it’s correct!

**Comment by djavorek** [comment]
This is still not the greatest.
Probably I will finish it when I am bored (HAHA)
